b= (input('Digite algo:'))
print('O tipo primitivo deste valor é:', type(b))
print('Só tem espaços?', b.isspace())
print('É um número?', b.isnumeric())
print('É alfabético?', b.isalpha())
print('É alfanumérico?', b.isalnum())
print('Está em maiúsculo?', b.isupper())
print('Está em minúnculo?', b.islower())
print('Está capitalizado?',b.istitle())